version: '3.8'

services:
  purchase:
    build:
      context: ./purchase
      dockerfile: Dockerfile
    ports:
      - "1000:1000"

  staff:
    build:
      context: ./staff
      dockerfile: Dockerfile
    ports:
      - "2000:2000"

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
